# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/availability-msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/availability-msgs.proto\x12\x05proto\"#\n\x10SiteAvailableReq\x12\x0f\n\x07site_id\x18\x01 \x01(\x03\"-\n\x10SiteAvailableRes\x12\x19\n\x04site\x18\x01 \x01(\x0b\x32\x0b.proto.Site\"\x13\n\x11SitesAvailableReq\"?\n\x11SitesAvailableRes\x12*\n\tresponses\x18\x01 \x03(\x0b\x32\x17.proto.SiteAvailableRes\"*\n\x04Site\x12\x0f\n\x07site_id\x18\x01 \x01(\x03\x12\x11\n\tavailable\x18\x02 \x01(\x08\x42\tZ\x07.;protob\x06proto3')



_SITEAVAILABLEREQ = DESCRIPTOR.message_types_by_name['SiteAvailableReq']
_SITEAVAILABLERES = DESCRIPTOR.message_types_by_name['SiteAvailableRes']
_SITESAVAILABLEREQ = DESCRIPTOR.message_types_by_name['SitesAvailableReq']
_SITESAVAILABLERES = DESCRIPTOR.message_types_by_name['SitesAvailableRes']
_SITE = DESCRIPTOR.message_types_by_name['Site']
SiteAvailableReq = _reflection.GeneratedProtocolMessageType('SiteAvailableReq', (_message.Message,), {
  'DESCRIPTOR' : _SITEAVAILABLEREQ,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SiteAvailableReq)
  })
_sym_db.RegisterMessage(SiteAvailableReq)

SiteAvailableRes = _reflection.GeneratedProtocolMessageType('SiteAvailableRes', (_message.Message,), {
  'DESCRIPTOR' : _SITEAVAILABLERES,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SiteAvailableRes)
  })
_sym_db.RegisterMessage(SiteAvailableRes)

SitesAvailableReq = _reflection.GeneratedProtocolMessageType('SitesAvailableReq', (_message.Message,), {
  'DESCRIPTOR' : _SITESAVAILABLEREQ,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SitesAvailableReq)
  })
_sym_db.RegisterMessage(SitesAvailableReq)

SitesAvailableRes = _reflection.GeneratedProtocolMessageType('SitesAvailableRes', (_message.Message,), {
  'DESCRIPTOR' : _SITESAVAILABLERES,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SitesAvailableRes)
  })
_sym_db.RegisterMessage(SitesAvailableRes)

Site = _reflection.GeneratedProtocolMessageType('Site', (_message.Message,), {
  'DESCRIPTOR' : _SITE,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.Site)
  })
_sym_db.RegisterMessage(Site)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007.;proto'
  _SITEAVAILABLEREQ._serialized_start=40
  _SITEAVAILABLEREQ._serialized_end=75
  _SITEAVAILABLERES._serialized_start=77
  _SITEAVAILABLERES._serialized_end=122
  _SITESAVAILABLEREQ._serialized_start=124
  _SITESAVAILABLEREQ._serialized_end=143
  _SITESAVAILABLERES._serialized_start=145
  _SITESAVAILABLERES._serialized_end=208
  _SITE._serialized_start=210
  _SITE._serialized_end=252
# @@protoc_insertion_point(module_scope)
