# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/registration-msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/registration-msgs.proto\x12\x05proto\"3\n\nSiteRegReq\x12\x0f\n\x07site_id\x18\x01 \x01(\x03\x12\x14\n\x0csite_ip_port\x18\x02 \x01(\t\"*\n\nSiteRegRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\tB\tZ\x07.;protob\x06proto3')



_SITEREGREQ = DESCRIPTOR.message_types_by_name['SiteRegReq']
_SITEREGRES = DESCRIPTOR.message_types_by_name['SiteRegRes']
SiteRegReq = _reflection.GeneratedProtocolMessageType('SiteRegReq', (_message.Message,), {
  'DESCRIPTOR' : _SITEREGREQ,
  '__module__' : 'proto.registration_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SiteRegReq)
  })
_sym_db.RegisterMessage(SiteRegReq)

SiteRegRes = _reflection.GeneratedProtocolMessageType('SiteRegRes', (_message.Message,), {
  'DESCRIPTOR' : _SITEREGRES,
  '__module__' : 'proto.registration_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SiteRegRes)
  })
_sym_db.RegisterMessage(SiteRegRes)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007.;proto'
  _SITEREGREQ._serialized_start=40
  _SITEREGREQ._serialized_end=91
  _SITEREGRES._serialized_start=93
  _SITEREGRES._serialized_end=135
# @@protoc_insertion_point(module_scope)
