# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/selector-verification-msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&proto/selector-verification-msgs.proto\x12\x05proto\"U\n\x17SelectorVerificationReq\x12\x0e\n\x06siteId\x18\x01 \x01(\x03\x12\x10\n\x08selector\x18\x02 \x01(\t\x12\x18\n\x10isSelectorString\x18\x03 \x01(\x08\"I\n\x17SelectorVerificationRes\x12\x0e\n\x06siteId\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"F\n\x18SelectorVerificationsReq\x12\x10\n\x08selector\x18\x01 \x01(\t\x12\x18\n\x10isSelectorString\x18\x02 \x01(\x08\"M\n\x18SelectorVerificationsRes\x12\x31\n\tresponses\x18\x01 \x03(\x0b\x32\x1e.proto.SelectorVerificationResB\tZ\x07.;protob\x06proto3')



_SELECTORVERIFICATIONREQ = DESCRIPTOR.message_types_by_name['SelectorVerificationReq']
_SELECTORVERIFICATIONRES = DESCRIPTOR.message_types_by_name['SelectorVerificationRes']
_SELECTORVERIFICATIONSREQ = DESCRIPTOR.message_types_by_name['SelectorVerificationsReq']
_SELECTORVERIFICATIONSRES = DESCRIPTOR.message_types_by_name['SelectorVerificationsRes']
SelectorVerificationReq = _reflection.GeneratedProtocolMessageType('SelectorVerificationReq', (_message.Message,), {
  'DESCRIPTOR' : _SELECTORVERIFICATIONREQ,
  '__module__' : 'proto.selector_verification_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SelectorVerificationReq)
  })
_sym_db.RegisterMessage(SelectorVerificationReq)

SelectorVerificationRes = _reflection.GeneratedProtocolMessageType('SelectorVerificationRes', (_message.Message,), {
  'DESCRIPTOR' : _SELECTORVERIFICATIONRES,
  '__module__' : 'proto.selector_verification_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SelectorVerificationRes)
  })
_sym_db.RegisterMessage(SelectorVerificationRes)

SelectorVerificationsReq = _reflection.GeneratedProtocolMessageType('SelectorVerificationsReq', (_message.Message,), {
  'DESCRIPTOR' : _SELECTORVERIFICATIONSREQ,
  '__module__' : 'proto.selector_verification_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SelectorVerificationsReq)
  })
_sym_db.RegisterMessage(SelectorVerificationsReq)

SelectorVerificationsRes = _reflection.GeneratedProtocolMessageType('SelectorVerificationsRes', (_message.Message,), {
  'DESCRIPTOR' : _SELECTORVERIFICATIONSRES,
  '__module__' : 'proto.selector_verification_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SelectorVerificationsRes)
  })
_sym_db.RegisterMessage(SelectorVerificationsRes)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007.;proto'
  _SELECTORVERIFICATIONREQ._serialized_start=49
  _SELECTORVERIFICATIONREQ._serialized_end=134
  _SELECTORVERIFICATIONRES._serialized_start=136
  _SELECTORVERIFICATIONRES._serialized_end=209
  _SELECTORVERIFICATIONSREQ._serialized_start=211
  _SELECTORVERIFICATIONSREQ._serialized_end=281
  _SELECTORVERIFICATIONSRES._serialized_start=283
  _SELECTORVERIFICATIONSRES._serialized_end=360
# @@protoc_insertion_point(module_scope)
